#Assignment 2 – Knowledge Graph

Perform Named-Entity Recognition (NER) on the corpus documents

Identify, and list, the en es and their labels that are recognized by spaCy’s default
medium-sized model (‘en_core_web_md’);

In [1]:
from src.Project2.ner_baseline import run_baseline_ner, summarize, save_entity_frequencies_to_csv
df = run_baseline_ner("../../data/train")
save_entity_frequencies_to_csv(df, "shakespeare_entities.csv")
summarize(df)

Looking in: E:\DigiPenMasterCourse\Semester4_2026\cs592_NLP\cs592-natural-language-processing\Chankasemporn_Ju-ve_CS592_NLP_Project\data\train
Matched files:
 - Shakespeare_Macbeth.txt
 - Shakespeare_Midsummer_Nights_Dream.txt
 - Shakespeare_Much_Ado_About_Nothing.txt
 - Shakespeare_Romeo_and_Juliet.txt
Loaded 4 text files
Processing: Shakespeare_Macbeth.txt
Processing: Shakespeare_Midsummer_Nights_Dream.txt
Processing: Shakespeare_Much_Ado_About_Nothing.txt
Processing: Shakespeare_Romeo_and_Juliet.txt
Saved entity frequencies to: shakespeare_entities.csv

=== Label Distribution ===
label
PERSON         2091
ORG             753
GPE             366
CARDINAL        250
DATE            230
TIME            198
ORDINAL         119
NORP             64
WORK_OF_ART      48
PRODUCT          44
LOC              17
LANGUAGE          9
QUANTITY          8
MONEY             5
EVENT             5
FAC               4
LAW               1
Name: count, dtype: int64

=== Entities with Frequency ===
                            entity       label  count
                          BENEDICK      PERSON    133
                             PEDRO      PERSON    120
                           CLAUDIO         ORG    104
                             NURSE         GPE     87
                             Romeo         ORG     74
                           Claudio      PERSON     73
                           CAPULET         ORG     68
                               one    CARDINAL     67
                          Benedick      PERSON     66
                             FIRST     ORDINAL     58
                               two    CARDINAL     50
                               DON      PERSON     48
                          Lysander      PERSON     47
                            Juliet      PERSON     45
                              JOHN      PERSON     45
                         DEMETRIUS         ORG     43
                           MALCOLM      PERSON     40
                              ROSS      PERSON     39
                            QUINCE      PERSON     38
                           Pyramus      PERSON     37
                             first     ORDINAL     35
                             Paris         GPE     34
                           tonight        TIME     32
                              Hero         ORG     30
                          tomorrow        DATE     30
                             night        TIME     30
                            OBERON      PERSON     29
                             Romeo      PERSON     28
                            Hermia      PERSON     26
                           THESEUS      PERSON     26
                            JULIET      PERSON     25
                          Beatrice      PERSON     24
                            Helena         ORG     24
                             PARIS         GPE     23
                         Demetrius         ORG     23
                            Banquo      PERSON     22
                               One    CARDINAL     22
                          Mercutio      PERSON     22
                           TITANIA         ORG     22
                          BENVOLIO      PERSON     21
                            Athens         GPE     20
                             Cupid         ORG     20
                          Margaret      PERSON     20
                           Macduff      PERSON     20
                         Don Pedro      PERSON     19
                             three    CARDINAL     19
                               May        DATE     19
                            Duncan      PERSON     18
                            DUNCAN      PERSON     18
                           Malcolm      PERSON     18
                          Don John      PERSON     17
                               Yea      PERSON     17
                           the day        DATE     17
                           Capulet      PERSON     17
                          Beatrice         ORG     17
                            morrow        DATE     17
                           Leonato      PERSON     17
                             Grace      PERSON     16
                         Demetrius      PERSON     16
                          Athenian        NORP     16
                          Montague         GPE     15
                         MESSENGER      PERSON     15
                            Hermia         GPE     15
                              HERO         ORG     14
                          Thursday        DATE     13
                          Farewell      PERSON     13
                            Mantua         GPE     13
                        this night        TIME     13
                              Puck      PERSON     13
                          MONTAGUE        DATE     12
                              Ross      PERSON     12
                            Lennox      PERSON     12
                            Oberon      PERSON     12
                               Two    CARDINAL     12
                             Nurse      PERSON     12
                          Scotland         GPE     11
                             Peter      PERSON     11
                          Lawrence      PERSON     11
                           THESEUS         ORG     11
                              Love WORK_OF_ART     11
                       GENTLEWOMAN      PERSON     11
                          Benvolio      PERSON     11
                              half    CARDINAL     11
                            SIWARD         ORG     11
                          Rosaline      PERSON     10
                            second     ORDINAL     10
                         Donalbain      PERSON     10
                              is’t         ORG     10
                            HERMIA         ORG     10
                            Ursula      PERSON     10
                              Hero      PERSON     10
                         the night        TIME      9
                             Helen      PERSON      9
                          MUSICIAN      PERSON      9
                            twenty    CARDINAL      9
                           Leonato         GPE      9
                              Dost      PERSON      9
                           Messina         GPE      9
                         Balthasar      PERSON      9
                              Wilt      PERSON      8
                      Peter Quince      PERSON      8
                              nine    CARDINAL      8
                             PETER      PERSON      8
                           Conrade      PERSON      8
                           England         GPE      8
                      Lady Macbeth      PERSON      8
                           Whither      PERSON      8
                              Is’t         ORG      8
                          Tomorrow        DATE      8
                           Titania     PRODUCT      7
                            Tybalt      PERSON      7
                          MARGARET      PERSON      7
                            Verona      PERSON      7
                             Sweet      PERSON      7
                             First     ORDINAL      7
                           Pyramus         ORG      7
                              John      PERSON      7
                             lov’d      PERSON      7
                               DON         ORG      6
                             Egeus      PERSON      6
                           Antonio         GPE      6
                          Montague      PERSON      6
                       PHILOSTRATE      PERSON      6
                        the County         GPE      6
                             Thane         GPE      6
                             today        DATE      6
                       FIRST WATCH         ORG      6
                            Bottom      PERSON      6
                      Lady Capulet      PERSON      6
                           Titania         ORG      6
                           Macbeth      PERSON      6
                          this day        DATE      6
                               ten    CARDINAL      6
                              bush      PERSON      6
                             Friar     PRODUCT      6
                            Seyton      PERSON      6
                            Sirrah      PERSON      5
                            Siward      PERSON      5
                              five    CARDINAL      5
                           an hour        TIME      5
                              four    CARDINAL      5
                            Nature WORK_OF_ART      5
                              Hero     PRODUCT      5
                           Alarums      PERSON      5
                           English    LANGUAGE      5
                             Angus      PERSON      5
                           GREGORY      PERSON      5
                            SEYTON      PERSON      5
                            French        NORP      5
                            Glamis      PERSON      5
                            Verona         GPE      5
                        last night        TIME      5
                             PETER         ORG      5
                            Prince      PERSON      5
                       Philostrate      PERSON      5
                          Hercules      PERSON      5
                             Venus     PRODUCT      5
                         Montagues      PERSON      4
                             Romeo     PRODUCT      4
                             Italy         GPE      4
                           morning        TIME      4
                          Borachio         GPE      4
                              holp      PERSON      4
                              Moon      PERSON      4
                             ANGUS         ORG      4
                              Jack      PERSON      4
                      Peaseblossom         ORG      4
                           Tonight        TIME      4
                           beshrew      PERSON      4
                      this morning        TIME      4
                            look’d      PERSON      4
                            twelve    CARDINAL      4
                       the morning        TIME      4
                            Hecate         ORG      4
                              Jove      PERSON      4
                             third     ORDINAL      4
                      PEASEBLOSSOM         ORG      4
                      Exit Servant      PERSON      4
                         Hippolyta         ORG      4
                        STARVELING         ORG      4
                             Friar    LANGUAGE      4
                              Lady      PERSON      4
                          fourteen        DATE      4
                       MUSTARDSEED         ORG      4
                          midnight        TIME      4
                           Cousins      PERSON      4
                           The day        DATE      3
                             Three    CARDINAL      3
                              Lest      PERSON      3
                             Lords         ORG      3
                      Sweet Prince      PERSON      3
                         every day        DATE      3
                           Swifter      PERSON      3
                           Leonato         ORG      3
                              Jule      PERSON      3
                             Tarry      PERSON      3
                        This night        TIME      3
                           nightly        TIME      3
                            Indian        NORP      3
                             Adieu      PERSON      3
                             eight    CARDINAL      3
                              Adam      PERSON      3
                    this afternoon        TIME      3
                             Troth      PERSON      3
                        Starveling         GPE      3
                            COBWEB         ORG      3
                            Birnam         GPE      3
                              Dian      PERSON      3
                          thousand    CARDINAL      3
                           Fortune WORK_OF_ART      3
                         CAITHNESS      PERSON      3
                            CHORUS         ORG      3
                             Robin      PERSON      3
                           Beshrew      PERSON      3
                         DONALBAIN      PERSON      3
                              Wall      PERSON      3
                     Friar Francis      PERSON      3
                             Queen      PERSON      3
                         Wednesday        DATE      3
                         this hour        TIME      3
                          Norweyan        NORP      3
                            SECOND        DATE      3
                             Ninny      PERSON      3
                             EGEUS         ORG      3
                             lulla      PERSON      3
                              Time         ORG      3
                     Enter Macbeth WORK_OF_ART      3
                      unaccustom’d         ORG      3
                            summer        DATE      3
                      ten thousand    CARDINAL      3
                            Monday        DATE      3
                               Tut      PERSON      3
                    tomorrow night        TIME      3
                           Gregory      PERSON      3
                             knell      PERSON      3
                          Hautboys      PERSON      2
                              gore      PERSON      2
                              Hero WORK_OF_ART      2
                           Ireland         GPE      2
                      half an hour        TIME      2
                             kerns         GPE      2
                            Hermia         ORG      2
                                ho      PERSON      2
                           Procrus      PERSON      2
                               fie         ORG      2
                  Robin Starveling      PERSON      2
                      Peaseblossom      PERSON      2
                                Ye      PERSON      2
                          Philomel      PERSON      2
                            Potpan      PERSON      2
                       Prince John      PERSON      2
                          Whate’er      PERSON      2
                          Prologue         ORG      2
                             Was’t      PERSON      2
                            Quince      PERSON      2
                           Villain      PERSON      2
              Saint Peter’s Church         ORG      2
                           a month        DATE      2
                             Scone         ORG      2
                           Tuesday        DATE      2
                            Sexton      PERSON      2
                            Sparta         GPE      2
                             Susan      PERSON      2
                        Sweet Hero      PERSON      2
                              Thou        NORP      2
                             Takes      PERSON      2
                            Tartar     PRODUCT      2
                             Thane      PERSON      2
                              Pale         ORG      2
                 a thousand ducats       MONEY      2
                         fairyland         GPE      2
                           Macduff         ORG      2
                           evening        TIME      2
                      eleven years        DATE      2
                     Lady Beatrice      PERSON      2
                     Lady Montague      PERSON      2
                           defil’d         GPE      2
                                Lo      PERSON      2
                               MAN         GPE      2
                          MERCUTIO      PERSON      2
                               Mab      PERSON      2
                           Macduff         GPE      2
                          braggart      PERSON      2
                  a thousand pound    QUANTITY      2
                              Mark      PERSON      2
                  Master Constable      PERSON      2
                         Misshapen      PERSON      2
                            awak’d      PERSON      2
                              Moth      PERSON      2
                           Neptune         LOC      2
                       Nick Bottom      PERSON      2
                            a week        DATE      2
                            Norway         GPE      2
                             Nurse         ORG      2
                        a thousand    CARDINAL      2
                                Ho      PERSON      2
                        The spring        DATE      2
                         Bergomask      PERSON      2
                           Ethiope         LOC      2
                            Europa         LOC      2
                          Evermore      PERSON      2
        Exeunt Dogberry and Verges WORK_OF_ART      2
                         Caithness         ORG      2
                            COUSIN        DATE      2
                            Birnam      PERSON      2
                     Exit Lysander      PERSON      2
                         Christian        NORP      2
                               Beg      PERSON      2
                        Attendants      PERSON      2
                  Exit Philostrate      PERSON      2
                         Exit Puck      PERSON      2
                           FLEANCE      PERSON      2
                       Fair Helena         ORG      2
                           Arragon         GPE      2
                            Ercles      PERSON      2
                             sixth     ORDINAL      2
                           Anthony      PERSON      2
                          that day        DATE      2
                   the hornèd moon      PERSON      2
                              Doth      PERSON      2
                          the hour        TIME      2
                         the hours        TIME      2
                          Descends      PERSON      2
                   the Fairy Queen WORK_OF_ART      2
                         that hour        TIME      2
                              East         LOC      2
                       Enter Nurse         ORG      2
                        ten nights        TIME      2
                             Crete         GPE      2
                   Enter Demetrius         ORG      2
                           thirdly     ORDINAL      2
                      Enter Helena         ORG      2
                         Constable      PERSON      2
                    Enter Montague         ORG      2
                           Antonio      PERSON      2
                    Exit Demetrius      PERSON      2
                         many days        DATE      2
                             years        DATE      2
                            winter        DATE      2
                            Glamis         GPE      2
                            Angus,         ORG      2
                           Fleance         ORG      2
                             Friar      PERSON      2
                         moonlight        TIME      2
                             was’t      PERSON      2
                        Friar John      PERSON      2
                              Wink      PERSON      1
                             Whole     PRODUCT      1
            yellow chapless skulls      PERSON      1
                              Will      PERSON      1

2. Identify and list, any en es that have been mislabeled by the default model;
3. Identify any en es that are missing labels, or do not have a default label to describe
their intended meaning;

In [2]:
from src.Project2.ner_mislabeled_finder import load_entity_csv, build_expected_entities, find_mislabeled_entities, find_missing_entities, find_no_good_default_label_entities

freq_df = load_entity_csv("shakespeare_entities.csv")
expected_entities = build_expected_entities()

mislabeled_df = find_mislabeled_entities(freq_df, expected_entities)
missing_df = find_missing_entities(freq_df, expected_entities)
no_default_df = find_no_good_default_label_entities(freq_df)

print("\n=== Step 2: Mislabeled Entities ===")
print(mislabeled_df.to_string(index=False))

print("\n=== Step 3A: Missing Entities ===")
print(missing_df.to_string(index=False))

print("\n=== Step 3B: No Good Default Label ===")
print(no_default_df.to_string(index=False))

=== Step 2: Mislabeled Entities ===
   entity predicted_label expected_label  count
  CLAUDIO             ORG         PERSON    104
    Romeo             ORG         PERSON     74
    Paris             GPE         PERSON     34
     Hero             ORG         PERSON     30
   Helena             ORG         PERSON     24
Demetrius             ORG         PERSON     23
    Cupid             ORG         PERSON     20
 Beatrice             ORG         PERSON     17
 Montague             GPE         PERSON     15
   Hermia             GPE         PERSON     15
     HERO             ORG         PERSON     14
  THESEUS             ORG         PERSON     11
  Leonato             GPE         PERSON      9
  Titania         PRODUCT         PERSON      7
   Verona          PERSON            GPE      7
  Pyramus             ORG         PERSON      7
      DON             ORG         PERSON      6
  Antonio             GPE         PERSON      6
  Titania             ORG         PERSON      6
    Friar         PRODUCT         PERSON      6
   Glamis          PERSON            GPE      5
     Hero         PRODUCT         PERSON      5
 Borachio             GPE         PERSON      4
    Friar        LANGUAGE         PERSON      4
    Romeo         PRODUCT         PERSON      4
  Leonato             ORG         PERSON      3
  Macduff             ORG         PERSON      2
   Birnam          PERSON            GPE      2
  Macduff             GPE         PERSON      2
    Nurse             ORG         PERSON      2
    Scone             ORG            GPE      2
   Hermia             ORG         PERSON      2
     Hero     WORK_OF_ART         PERSON      2
   Tybalt         PRODUCT         PERSON      1
     Fife            NORP            GPE      1
 BENEDICK             ORG         PERSON      1
   Helena             GPE         PERSON      1
    Romeo           EVENT         PERSON      1
    Scone          PERSON            GPE      1
   Oberon             GPE         PERSON      1
 Montague             ORG         PERSON      1
  Macbeth             GPE         PERSON      1

=== Step 3A: Missing Entities ===
 entity expected_label                     issue
 Forres            GPE Missing from spaCy output
  Pedro         PERSON Missing from spaCy output
Theseus         PERSON Missing from spaCy output

=== Step 3B: No Good Default Label ===
        entity   label  count                                                                                      reason
         FIRST ORDINAL     58 Role/stage-direction entity; spaCy default labels do not describe its intended meaning well
     MESSENGER  PERSON     15 Role/stage-direction entity; spaCy default labels do not describe its intended meaning well
   GENTLEWOMAN  PERSON     11 Role/stage-direction entity; spaCy default labels do not describe its intended meaning well
        second ORDINAL     10 Role/stage-direction entity; spaCy default labels do not describe its intended meaning well
      MUSICIAN  PERSON      9 Role/stage-direction entity; spaCy default labels do not describe its intended meaning well
         First ORDINAL      7 Role/stage-direction entity; spaCy default labels do not describe its intended meaning well
  Exit Servant  PERSON      4 Role/stage-direction entity; spaCy default labels do not describe its intended meaning well
    Attendants  PERSON      2 Role/stage-direction entity; spaCy default labels do not describe its intended meaning well
       Witches  PERSON      1 Role/stage-direction entity; spaCy default labels do not describe its intended meaning well
         Witch  PERSON      1 Role/stage-direction entity; spaCy default labels do not describe its intended meaning well
 Exit Murderer     ORG      1 Role/stage-direction entity; spaCy default labels do not describe its intended meaning well
BOTH MURDERERS     ORG      1 Role/stage-direction entity; spaCy default labels do not describe its intended meaning well
     Messenger  PERSON      1 Role/stage-direction entity; spaCy default labels do not describe its intended meaning well
      MURDERER     ORG      1 Role/stage-direction entity; spaCy default labels do not describe its intended meaning well

4. For all en es iden fied in step 3 above, fine-tune the model to correct any
- Mislabeled entities ,
- Missing-label entities ,
- Pronoun resolution, coreference resolution – go beyond the ‘1-sentence-back’ model to write your own custom code for pronoun resolution.

5. List out all the entities with their appropriate labels. Use a spreadsheet/table to include this informa on in your report

In [3]:
from src.Project2.ner_finetuning import load_corpus_text, build_training_examples_from_text, build_training_examples_from_corpus, combine_training_examples, TRAIN_DATA,  resolve_pronouns_custom, fine_tune_shakespeare_ner, export_final_entity_table

data_dir = '../../data/train'
corpus_text = load_corpus_text(data_dir)

weak_examples_text = build_training_examples_from_text(corpus_text, expected_entities, window_size=300, max_examples_per_entity=10)
len(weak_examples_text), weak_examples_text[:3]

(3000, 1006)

In [ ]:
weak_examples_sent = build_training_examples_from_corpus(corpus_text, expected_entities, min_entities_per_example=1, max_examples=3000)
training_data = combine_training_examples(TRAIN_DATA, weak_examples_sent)
len(weak_examples_sent), len(training_data)

In [4]:
nlp_ft = fine_tune_shakespeare_ner(
    train_data=training_data,
    output_dir='shakespeare_ner_model',
    base_model='en_core_web_md',
    n_iter=40,
    entity_labels=expected_entities,
)

sample_text = corpus_text[:10000]
doc = nlp_ft(sample_text)
coref_df = resolve_pronouns_custom(doc)
coref_df.head(30)

C:\Users\drago\AppData\Local\Programs\Python\Python39\lib\site-packages\spacy\training\iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Now, good sweet Nurse,—O Lord, why look’st thou sa..." with entities "[(16, 21, 'PERSON')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
C:\Users\drago\AppData\Local\Programs\Python\Python39\lib\site-packages\spacy\training\iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Speak, Pyramus.—Thisbe, stand forth." with entities "[(7, 14, 'PERSON')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
C:\Users\drago\AppData\Local\Programs\Python\Python39\lib\site-packages\spacy\training\iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Anon, good Nurse!—Sweet Montague be true." with entities "[(11, 16, 'PERSON'), (24, 32, 'PERSON')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
C:\Users\drago\AppData\Local\Programs\Python\Python39\lib\site-packages\spacy\training\iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "You speak all your part at once, cues, and all.—Py..." with entities "[(48, 55, 'PERSON')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
C:\Users\drago\AppData\Local\Programs\Python\Python39\lib\site-packages\spacy\training\iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "The gracious Duncan Was pitied of Macbeth:—marry, ..." with entities "[(13, 19, 'PERSON'), (34, 41, 'PERSON'), (86, 92, ...". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
C:\Users\drago\AppData\Local\Programs\Python\Python39\lib\site-packages\spacy\training\iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "These evils thou repeat’st upon thyself Have banis..." with entities "[(62, 70, 'GPE')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
C:\Users\drago\AppData\Local\Programs\Python\Python39\lib\site-packages\spacy\training\iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "How far is’t call’d to Forres?—What are these, So ..." with entities "[(23, 29, 'GPE')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
C:\Users\drago\AppData\Local\Programs\Python\Python39\lib\site-packages\spacy\training\iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Go you to the Prince your brother; spare not to te..." with entities "[(115, 122, 'PERSON'), (205, 209, 'PERSON')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(
C:\Users\drago\AppData\Local\Programs\Python\Python39\lib\site-packages\spacy\training\iob_utils.py:149: UserWarning: [W030] Some entities could not be aligned in the text "Beware Macduff; Beware the Thane of Fife.—Dismiss ..." with entities "[(7, 14, 'PERSON'), (36, 40, 'GPE')]". Use `spacy.training.offsets_to_biluo_tags(nlp.make_doc(text), entities)` to check the alignment. Misaligned entities ('-') will be ignored during training.
  warnings.warn(

Iteration 1/20 - Losses: {'ner': 1685.3299407177692}
Iteration 2/20 - Losses: {'ner': 1160.2082923735998}
Iteration 3/20 - Losses: {'ner': 984.0244489713456}
Iteration 4/20 - Losses: {'ner': 836.4153736407044}
Iteration 5/20 - Losses: {'ner': 776.5605291030868}
Iteration 6/20 - Losses: {'ner': 606.998570158244}
Iteration 7/20 - Losses: {'ner': 558.0560169416656}
Iteration 8/20 - Losses: {'ner': 530.0368708319521}
Iteration 9/20 - Losses: {'ner': 485.9877083021155}
Iteration 10/20 - Losses: {'ner': 385.17661878621533}
Iteration 11/20 - Losses: {'ner': 367.3390066469395}
Iteration 12/20 - Losses: {'ner': 346.4954393347143}
Iteration 13/20 - Losses: {'ner': 292.5587860177532}
Iteration 14/20 - Losses: {'ner': 268.92969737183273}
Iteration 15/20 - Losses: {'ner': 247.46321400270102}
Iteration 16/20 - Losses: {'ner': 230.56479004904506}
Iteration 17/20 - Losses: {'ner': 217.53926599791612}
Iteration 18/20 - Losses: {'ner': 182.664024449268}
Iteration 19/20 - Losses: {'ner': 174.84783918312223}
Iteration 20/20 - Losses: {'ner': 151.54396145366695}
Saved fine-tuned model to E:\DigiPenMasterCourse\Semester4_2026\cs592_NLP\cs592-natural-language-processing\Chankasemporn_Ju-ve_CS592_NLP_Project\src\Project2\shakespeare_ner_model

,pronoun,sentence,resolved_to,rationale
0,He,"He can report, As seemeth by his plight, of th...",DUNCAN,Most recent male-compatible entity in rolling ...
1,his,"He can report, As seemeth by his plight, of th...",DUNCAN,Most recent male-compatible entity in rolling ...
2,he,But all’s too weak; For brave Macbeth (well he...,Macbeth,Most recent male-compatible entity in rolling ...
3,his,But all’s too weak; For brave Macbeth (well he...,Macbeth,Most recent male-compatible entity in rolling ...
4,his,But all’s too weak; For brave Macbeth (well he...,Macbeth,Most recent male-compatible entity in rolling ...
5,he,But all’s too weak; For brave Macbeth (well he...,Macbeth,Most recent male-compatible entity in rolling ...
6,him,But all’s too weak; For brave Macbeth (well he...,Macbeth,Most recent male-compatible entity in rolling ...
7,he,But all’s too weak; For brave Macbeth (well he...,Macbeth,Most recent male-compatible entity in rolling ...
8,him,But all’s too weak; For brave Macbeth (well he...,Macbeth,Most recent male-compatible entity in rolling ...
9,his,But all’s too weak; For brave Macbeth (well he...,Macbeth,Most recent male-compatible entity in rolling ...
10,his,As whence the sun ’gins his reflection Shipwra...,DUNCAN,Most recent male-compatible entity in rolling ...
11,their,"Mark, King of Scotland, mark: No sooner justic...",SOLDIER and Mark,Two most recent person-like entities in rollin...
12,they,"If I say sooth, I must report they were As can...",Banquo and SOLDIER,Two most recent person-like entities in rollin...
13,they,"If I say sooth, I must report they were As can...",Banquo and SOLDIER,Two most recent person-like entities in rollin...
14,they,"If I say sooth, I must report they were As can...",Banquo and SOLDIER,Two most recent person-like entities in rollin...
15,They,So well thy words become thee as thy wounds: T...,SOLDIER and DUNCAN,Two most recent person-like entities in rollin...
16,him,So well thy words become thee as thy wounds: T...,DUNCAN,Most recent male-compatible entity in rolling ...
17,his,What a haste looks through his eyes!,LENNOX,Most recent male-compatible entity in rolling ...
18,he,So should he look That seems to speak things s...,LENNOX,Most recent male-compatible entity in rolling ...
19,him,"Norway himself, with terrible numbers, Assiste...",ROSS,Most recent male-compatible entity in rolling ...
20,his,"Norway himself, with terrible numbers, Assiste...",ROSS,Most recent male-compatible entity in rolling ...
21,him,"That now Sweno, the Norways’ king, craves comp...",ROSS,Most recent male-compatible entity in rolling ...
22,his,"That now Sweno, the Norways’ king, craves comp...",ROSS,Most recent male-compatible entity in rolling ...
23,he,"That now Sweno, the Norways’ king, craves comp...",ROSS,Most recent male-compatible entity in rolling ...
24,his,"Go pronounce his present death, And with his f...",Macbeth,Most recent male-compatible entity in rolling ...
25,his,"Go pronounce his present death, And with his f...",Macbeth,Most recent male-compatible entity in rolling ...
26,he,"What he hath lost, noble Macbeth hath won.",Macbeth,Most recent male-compatible entity in rolling ...
27,their,"How far is’t call’d to Forres?—What are these,...",MACBETH and BANQUO,Two most recent person-like entities in rollin...
28,he,My noble partner You greet with present grace ...,BANQUO,Most recent male-compatible entity in rolling ...
29,they,Would they had stay’d! BANQUO.,MACBETH and BANQUO,Two most recent person-like entities in rollin...

In [5]:
final_entities_df = export_final_entity_table(
    text=corpus_text,
    model_path='shakespeare_ner_model',
    output_csv='final_entities.csv'
)
final_entities_df.head(50)

Saved final entity table to E:\DigiPenMasterCourse\Semester4_2026\cs592_NLP\cs592-natural-language-processing\Chankasemporn_Ju-ve_CS592_NLP_Project\src\Project2\final_entities.csv

            entity   label  frequency
0           Athens     GPE         20
1           Aurora     GPE          1
2        Betroth’d     GPE          1
3           Birnam     GPE         10
4            Crete     GPE          2
5            Egypt     GPE          1
6          England     GPE          8
7             Fife     GPE          4
8           Glamis     GPE          8
9        Hobgoblin     GPE          1
10           India     GPE          1
11       Inverness     GPE          1
12           Italy     GPE          4
13          Mantua     GPE         13
14         Messina     GPE          9
15           Milan     GPE          1
16  Northumberland     GPE          1
17          Norway     GPE          2
18         Norways     GPE          1
19         Pharaoh     GPE          1
20           Quail     GPE          1
21           Scone     GPE          3
22        Scotland     GPE         11
23         Seacoal     GPE          1
24         Shoughs     GPE          1
25          Sparta     GPE          2
26           Thane     GPE          1
27           Titan     GPE          1
28          Venice     GPE          1
29          Verona     GPE         12
30         quondam     GPE          1
31           ANGUS  PERSON          4
32         ANTONIO  PERSON          4
33      APOTHECARY  PERSON          4
34           Abram  PERSON          1
35         Acheron  PERSON          1
36            Adam  PERSON          3
37          Aegles  PERSON          1
38         Alarums  PERSON          5
39        Angelica  PERSON          1
40           Angus  PERSON          3
41         Anthony  PERSON          2
42       Antipodes  PERSON          2
43         Antonio  PERSON          9
44          Apollo  PERSON          1
45         Ariadne  PERSON          1
46          Augurs  PERSON          1
47          Aurora  PERSON          1
48       BALTHASAR  PERSON         23
49          BANQUO  PERSON         33